
CREATE DATABASE chatting_with_emotion DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

USE chatting_with_emotion;

CREATE TABLE User (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    UserName VARCHAR(20) NOT NULL,
    RegistrationDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    LoginID VARCHAR(20) UNIQUE NOT NULL,
    LoginPW VARCHAR(255) NOT NULL
);

CREATE TABLE Room (
    RoomID INT AUTO_INCREMENT PRIMARY KEY,
    HostID INT NOT NULL,
    RoomName VARCHAR(30) NOT NULL,
    RoomCreationDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (HostID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE UserRoom (
    UserID INT NOT NULL,
    RoomID INT NOT NULL,
    Valid BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (UserID, RoomID),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (RoomID) REFERENCES Room(RoomID) ON DELETE CASCADE
);

CREATE TABLE Chat (
    ChatID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    RoomID INT NOT NULL,
    ChatContent TEXT NOT NULL,
    ChatDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    ChatMood VARCHAR(10),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (RoomID) REFERENCES Room(RoomID) ON DELETE CASCADE
);

CREATE TABLE Markov (
    UserID INT NOT NULL,
    RoomID INT NOT NULL,
    KovData JSON,
    PRIMARY KEY (UserID, RoomID),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (RoomID) REFERENCES Room(RoomID) ON DELETE CASCADE
);
